version: 4.5.18.{build}

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2022

clone_depth: 1
clone_folder: C:\build

build_script:
- cmd: cd Build && Build.bat pre 0 0 0 0 1

test_script:
- cmd: vstest.console /logger:Appveyor x32-Debug\Obj\Common_Test\Common_Test.dll
