version: 4.5.18-{build}

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+\.\d+\.

image: Visual Studio 2022

clone_depth: 1
clone_folder: C:\build

build_script:
- cmd: cd Build && Build.bat ci

artifacts:
  - path: Build/Rainmeter-*.exe

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/2d37d539-98b7-4649-9469-4097b1099202/Integrations/AppVeyor?ProjectSlug=rainmeter&SigningPolicySlug=release-signing
  authorization:
     secure: YnZH/YJ9Me+6CY6WhyO44nJjzjquWn7IGGxaj3xDT/JOUVMMB5IBf2GVQwutF/l26WstrHNmaFZCGTMvXuc4Cg==
  on:
    APPVEYOR_REPO_TAG: true
